// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer_history.proto

package com.debezium.application.proto;

public final class CustomerHistoryEventWrapper {
  private CustomerHistoryEventWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_application_OrderHistoryEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_application_OrderHistoryEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026customer_history.proto\022\013application\"w\n" +
      "\021OrderHistoryEvent\022\020\n\010order_id\030\001 \001(\t\022\022\n\n" +
      "order_name\030\002 \001(\t\022\023\n\013customer_id\030\003 \001(\t\022\024\n" +
      "\014order_status\030\004 \001(\t\022\021\n\toperation\030\005 \001(\tB?" +
      "\n\036com.debezium.application.protoB\033Custom" +
      "erHistoryEventWrapperP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_application_OrderHistoryEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_application_OrderHistoryEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_application_OrderHistoryEvent_descriptor,
        new java.lang.String[] { "OrderId", "OrderName", "CustomerId", "OrderStatus", "Operation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
